# Generated by Django 5.2.7 on 2025-10-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=200.0, max_digits=10, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('clothing', 'clothing'), ('shoes', 'shoes'), ('accessories', 'accessories'), ('jewelry', 'jewelry'), ('watches', 'watches')], default='clothing', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('brief_note', models.CharField(blank=True, default='Just In', max_length=255, null=True)),
            ],
        ),
    ]
