# Generated by Django 5.2.7 on 2025-10-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('clothing', 'clothing'), ('shoes', 'shoes'), ('accessories', 'accessories'), ('jewelry', 'jewelry'), ('watches', 'watches'), ('headwear', 'headwear')], default='clothing', max_length=50),
        ),
    ]
