# Generated by Django 5.2.7 on 2025-10-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0004_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(default='size do not apply', max_length=255),
        ),
    ]
