# Generated by Django 5.2.7 on 2025-10-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0007_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
