# Generated by Django 5.2.7 on 2025-10-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0009_checkoutaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutaddress',
            old_name='additional_number',
            new_name='additional_phone_number',
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='additional_information',
            field=models.TextField(default='No Additional Information from user'),
        ),
    ]
