# Generated by Django 5.2.7 on 2025-10-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0010_rename_additional_number_checkoutaddress_additional_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutaddress',
            name='address',
            field=models.CharField(default='No address', max_length=255),
        ),
    ]
