# Generated by Django 5.2.7 on 2025-10-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0011_checkoutaddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='additional_phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
