# Generated by Django 5.2.7 on 2025-10-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0012_alter_checkoutaddress_additional_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='additional_phone_number',
            field=models.CharField(default='no addtional phone number', max_length=10),
        ),
    ]
