# Generated by Django 5.2.7 on 2025-10-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0013_alter_checkoutaddress_additional_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutaddress',
            old_name='user',
            new_name='added_by',
        ),
    ]
