# Generated by Django 5.2.7 on 2025-11-01 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0014_rename_user_checkoutaddress_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_store.products')),
            ],
        ),
    ]
