# Generated by Django 5.2.7 on 2025-11-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0015_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_verified_for_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
