# Generated by Django 5.2.7 on 2025-11-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0016_customuser_otp_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='none', null=True, upload_to=''),
        ),
    ]
