# Generated by Django 5.2.7 on 2025-11-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0018_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_email_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
